env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
